Add bookings
Gmilovidov/java-shareit pull request #3
Opened 2024-05-24 15:17 UTC by Gmilovidov

Решилне использовать мапстракт на booking,  код усложняется(особенно если 3 дто) и апдейт криво работает, или я что то не понимаю, прошу позволить мне работать с ручными мапперами мне так понятней и удобней

2024-05-24 22:22 UTC, andrew-larkin requested changes
Привет! Очень хорошая реализация нового функционала! В паре мест посмотреть/поправить и сможем двигаться дальше.

2024-05-24 22:22 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
тут все еще рекомендую воспользоваться mapStruct

2024-05-24 22:22 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public void delete(@PathVariable Long id) {
здесь тоже можно использовать ResponseBody. Используй тип Void и метод .noContent().build()

2024-05-25 13:30 UTC, Gmilovidov commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
я психанул и все получилось)))) не понимаю что раньше не так делал.....

2024-05-26 16:05 UTC, merged